'use client'
import React from "react";
import "~/styles/globals.css";
import { Geist } from "next/font/google";
import {HeroUIProvider} from "@heroui/react";
import Nav from "~/components/nav";

// export const metadata: Metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };
const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
      <html lang="en" className={`${geist.variable}`}>
        <body>
          <HeroUIProvider>
            <Nav />
            {children}
          </HeroUIProvider>
        </body>
      </html>
  );
}
